const res = {
  "Url 1": "Dolore rerum consequ",
  "Url 2": "Officia blanditiis s",
  "Url 3": "Illo sit corrupti v",
  address: "Assumenda eum porro ",
  business_level: "Small",
  business_type: "Enterpreneur",
  cac_doc: "332323312",
  ceo_gender: "male",
  ceo_image: {},
  ceo_name: "Darrel Sutton",
  company_logo: {},
  company_valuation: "₦20000",
  currency: "₦",
  currency_value: 2000000,
  description: "Id consectetur ipsa",
  ecosystem: "",
  email: "lyzuvu@mailinator.com",
  facebook: "Odit eum dolor minim",
  funding: "₦2000000",
  headquarters: "",
  instagram: "Enim quis dolor duci",
  is_active: true,
  is_ecosystem: false,
  is_enterpreneur: true,
  is_startup: "Yes",
  linkedin: "Elit sit inventore",
  name: "Kermit Johnston",
  num_of_employees: "1-100",
  num_supported_business: "",
  phone: "+1 (858) 671-3572",
  sector: 53,
  state: "Abuja",
  sub_ecosystem: "",
  sub_ecosystem_sub_class: null,
  sub_segment: "",
  twitter: "Qui sint praesentium",
  user: "",
  website: "https://www.tywizivogojo.org.uk",
};

export { res };
