export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERROR";
export const RESET_ERROR = "RESET_ERROR";

export const GET_ALL_ECOSYSTEM = "GET_ALL_ECOSYSTEM";
export const GET_ALL_SUB_ECOSYSTEM = "GET_ALL_SUB_ECOSYSTEM";
export const GET_ALL_ORGANIZATION = "GET_ALL_ORGANIZATION";
